version: '3.8'

services:
  frontend:
    build:
      context: ./scraper-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - MYSQL_USER=scraper_user
      - MYSQL_PASSWORD=scraper_password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=scraper_db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=scraper_user
      - MYSQL_PASSWORD=scraper_password
      - MYSQL_DATABASE=scraper_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  mysql_data: